import { APP_NAME } from "../../constants/app";
import { formatCurrency, formatDate, capitalize } from "../../utils/format";

/** Minimal escaping — invoice fields are user data going into an HTML document. */
function escapeHtml(value) {
  return String(value ?? "").replace(
    /[&<>"']/g,
    (char) =>
      ({
        "&": "&amp;",
        "<": "&lt;",
        ">": "&gt;",
        '"': "&quot;",
        "'": "&#39;",
      })[char],
  );
}

/**
 * Opens a print-ready invoice in a new window and triggers the print dialog,
 * where the browser's own "Save as PDF" produces a real PDF.
 *
 * Returns false when the pop-up was blocked, so the caller can say so.
 */
export function printInvoice(invoice) {
  const win = window.open("", "_blank", "width=820,height=900");
  if (!win) return false;

  win.document.write(`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${escapeHtml(invoice.id)}</title>
<style>
  body { font-family: -apple-system, "Segoe UI", Roboto, sans-serif; color: #0f172a; margin: 0; padding: 48px; }
  header { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #e5e7eb; padding-bottom: 24px; }
  h1 { font-size: 28px; margin: 0; }
  .muted { color: #6b7280; font-size: 13px; }
  .id { font-size: 15px; font-weight: 600; margin-top: 4px; }
  table { border-collapse: collapse; margin-top: 32px; width: 100%; }
  th, td { border-bottom: 1px solid #e5e7eb; padding: 12px 8px; text-align: left; }
  th { color: #6b7280; font-size: 12px; letter-spacing: .04em; text-transform: uppercase; }
  .total td { border-bottom: none; font-size: 18px; font-weight: 700; padding-top: 20px; }
  .right { text-align: right; }
  footer { color: #6b7280; font-size: 12px; margin-top: 48px; }
  @media print { body { padding: 0; } }
</style>
</head>
<body>
  <header>
    <div>
      <h1>Invoice</h1>
      <div class="id">${escapeHtml(invoice.id)}</div>
    </div>
    <div class="right">
      <strong>${escapeHtml(APP_NAME)}</strong>
      <div class="muted">support@naytak.io</div>
    </div>
  </header>

  <table>
    <tr><th>Billed to</th><th>Issued</th><th>Due</th><th class="right">Status</th></tr>
    <tr>
      <td>${escapeHtml(invoice.customer)}</td>
      <td>${escapeHtml(formatDate(invoice.issued))}</td>
      <td>${escapeHtml(formatDate(invoice.due))}</td>
      <td class="right">${escapeHtml(capitalize(invoice.status))}</td>
    </tr>
    <tr class="total">
      <td colspan="3">Amount due</td>
      <td class="right">${escapeHtml(formatCurrency(invoice.amount))}</td>
    </tr>
  </table>

  <footer>Generated by ${escapeHtml(APP_NAME)} on ${escapeHtml(formatDate(new Date()))}.</footer>
</body>
</html>`);
  win.document.close();
  win.focus();
  // Let the new document lay out before the dialog opens.
  win.setTimeout(() => win.print(), 200);
  return true;
}
