/**
 * Export helper for the navbar "Download" button.
 *
 * The whole project source (excluding node_modules, dist, .git) is zipped at
 * build/dev time by the `projectZipPlugin` Vite plugin and served from
 * `public/project-source.zip`. This module just fetches that archive and
 * triggers a download — unzip it and run `npm install && npm start` to boot
 * the full admin template locally.
 */

/** Trigger a browser download of a Blob. */
function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/**
 * Download the runnable project source as a ZIP.
 * The archive is generated by the Vite plugin (projectZipPlugin) from the real
 * project files — node_modules / dist are excluded, so it is ready to run.
 */
export async function downloadProjectSource() {
  const response = await fetch("./project-source.zip");
  if (!response.ok) {
    throw new Error(`Project archive unavailable (HTTP ${response.status})`);
  }
  const blob = await response.blob();
  downloadBlob(blob, "naytak-admin-template.zip");
}
